# Generated by Django 5.2.5 on 2025-08-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batting', models.IntegerField()),
                ('bowling', models.IntegerField()),
                ('runs', models.IntegerField()),
            ],
        ),
    ]
