# Generated by Django 5.2.5 on 2025-08-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7app', '0002_playercard_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('player_card_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=100)),
                ('computer_card_id', models.IntegerField()),
                ('computer_name', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
