# Generated by Django 6.0.3 on 2026-05-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7app', '0005_team_playercard_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='ability',
            field=models.CharField(choices=[('none', 'No Ability'), ('opener', 'Opener'), ('finisher', 'Finisher'), ('mid_over_hitter', 'Mid Over Hitter'), ('spin_basher', 'Spin Basher'), ('saviour', 'Saviour'), ('powerplay_specialist', 'Powerplay Specialist'), ('death_specialist', 'Death Specialist'), ('mid_over_specialist', 'Mid Over Specialist'), ('runs_cutter', 'Runs Cutter'), ('golden_arm', 'Golden Arm'), ('breakthrough', 'Breakthrough')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='playercard',
            name='is_spinner',
            field=models.BooleanField(default=False),
        ),
    ]
