# Generated by Django 6.0.3 on 2026-05-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7app', '0006_playercard_ability_playercard_is_spinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('support_type', models.CharField(choices=[('batting_support', 'Batting Support'), ('pace_support', 'Pace Support'), ('spin_support', 'Spin Support')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='support_cards/')),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
