# Generated by Django 6.0.3 on 2026-05-30 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7app', '0007_supportcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='weightage',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_prize', models.BooleanField(default=False)),
                ('slot', models.IntegerField(blank=True, null=True)),
                ('player_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s7app.playercard')),
            ],
        ),
        migrations.CreateModel(
            name='UserDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('cards', models.ManyToManyField(through='s7app.DeckCard', to='s7app.playercard')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s7app.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deckcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s7app.userdeck'),
        ),
        migrations.AddConstraint(
            model_name='userdeck',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='unique_user_team_deck'),
        ),
        migrations.AlterUniqueTogether(
            name='deckcard',
            unique_together={('deck', 'player_card')},
        ),
    ]
