# Generated by Django 6.0.3 on 2026-05-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7app', '0008_playercard_weightage_deckcard_userdeck_deckcard_deck_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckcard',
            name='is_prize',
        ),
        migrations.AddField(
            model_name='playercard',
            name='is_prize_card',
            field=models.BooleanField(default=False),
        ),
    ]
