# Generated by Django 6.0.3 on 2026-05-30 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7app', '0009_remove_deckcard_is_prize_playercard_is_prize_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercard',
            name='is_prize_card',
        ),
        migrations.CreateModel(
            name='UserPrizeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prize_slots', to='s7app.userdeck')),
                ('player_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s7app.playercard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'player_card')},
            },
        ),
    ]
