# Generated by Django 6.0.3 on 2026-06-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7app', '0010_remove_playercard_is_prize_card_userprizecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Player 2'), ('live', 'Live Match'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
