# Generated by Django 6.0.3 on 2026-06-05 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7app', '0011_gameroom_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='player1_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_p1', to='s7app.userdeck'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='player2_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_p2', to='s7app.userdeck'),
        ),
    ]
