# Generated by Django 6.0.6 on 2026-08-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s7app', '0012_gameroom_player1_deck_gameroom_player2_deck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameHistory',
        ),
    ]
