# Generated by Django 6.0.6 on 2026-08-28 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s7app', '0013_delete_gamehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_season_at_a_time')],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('format', models.CharField(choices=[('round_robin', 'Round Robin'), ('knockout', 'Knockout')], max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('max_participants', models.PositiveIntegerField()),
                ('seeding_method', models.CharField(choices=[('manual', 'Manual (admin sets seed order)')], default='manual', max_length=20)),
                ('seeding_locked', models.BooleanField(default=False, help_text='Set True the moment fixtures are generated. No participant/seed changes after this.')),
                ('points_win', models.PositiveIntegerField(default=2)),
                ('points_tie', models.PositiveIntegerField(default=1)),
                ('points_loss', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('rules_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hosted_by', models.ForeignKey(help_text='Must be a staff/admin account — enforce at the view layer.', on_delete=django.db.models.deletion.PROTECT, related_name='hosted_tournaments', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='s7app.season')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField(blank=True, help_text='Set manually by the admin before the tournament starts. Determines bracket/pairing order.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('eliminated', 'Eliminated'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(blank=True, help_text='Deck locked in for this tournament. Optional until the player confirms one.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='s7app.userdeck')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='s7app.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['seed', 'joined_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['upcoming', 'ongoing'])), fields=('status',), name='one_active_tournament_at_a_time'),
        ),
        migrations.AddConstraint(
            model_name='tournamentparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('seed__isnull', False)), fields=('tournament', 'seed'), name='unique_seed_per_tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together={('tournament', 'user')},
        ),
    ]
