"""
Django settings for s7 project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent



SECRET_KEY = 'django-insecure-+hs*cs+ey6)@3bjq5e5n*)rz@31##9jgllrs+nk#nh6wqip8l5'

DEBUG = True     # Set to True for local development to see detailed errors
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'super7.onrender.com', 's7multi.onrender.com']  # Add local hosts and Render domain

# HTTPS and proxy settings
SECURE_SSL_REDIRECT = False  # Disable for local testing (no HTTPS needed); set to True for Render if needed
SECURE_PROXY_SSL_HEADER = None  # Disable proxy header locally; set to ('HTTP_X_FORWARDED_PROTO', 'https') for Render
CSRF_COOKIE_SECURE = False  # Allow cookies over HTTP locally; set to True for Render
SESSION_COOKIE_SECURE = False  # Allow session cookies over HTTP locally; set to True for Render
CSRF_TRUSTED_ORIGINS = ['http://localhost', 'http://127.0.0.1', 'https://s7multi.onrender.com','https://super7.onrender.com']  # Trust local origins and Render domain
SECURE_HSTS_SECONDS = 0  # Disable HSTS locally; set to a value (e.g., 31536000) for Render if needed
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# Application definition
INSTALLED_APPS = [
    'daphne',          
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    's7app'
]
ASGI_APPLICATION = 's7.asgi.application'

REDIS_URL = os.getenv('REDIS_URL', '')

if REDIS_URL:
    # Cache — django-redis (works fine with Upstash)
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': True,
                'CONNECTION_POOL_KWARGS': {
                    'ssl_cert_reqs': None,
                    'socket_timeout': 5,
                    'socket_connect_timeout': 5,
                },
            },
            'KEY_PREFIX': 's7',
        }
    }

    # Channel layers — use InMemoryChannelLayer on production too
    # Upstash free tier times out with channels_redis persistent connections
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }

else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 's7.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 's7.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url
import os

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=0,
    )
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = 'static/'
# settings.py
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Where files are stored on the filesystem
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
